import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { AppProviders } from "@/contexts/AppProviders";
import AppRedirect from "@/components/app-redirect/AppRedirect";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Footscribe90",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script
          src="https://accounts.google.com/gsi/client"
          async
          defer
        ></script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppProviders>
          <AppRedirect>{children}</AppRedirect>
        </AppProviders>
      </body>
    </html>
  );
}
